### ISSUE TITLE
get data

### ISSUE THREAD

**Issue by suweiaiyishujia** [JoiDvision/BNN_CamModel#2]
how can i get the cam picture in this project?

**Comment by jiarongp** [comment]
Hi, for the downloading of images from Dresden Image Database, the corresponding function is [here](https://github.com/JoiDvision/BNN_CamModel/blob/78c54fee661da51c14423f2284f25aa04a29c69b/dataloader_lib.py#L64). 

However, this dataset is unfortunately not available anymore. So if you still  want to use our method, you might need a different dataset, but the algorithm will still work the same. [RAISE](http://loki.disi.unitn.it/RAISE/download.html) and [The Forcheim Image Database](https://arxiv.org/abs/2011.02241l) are two possible substitutes.

**Comment by suweiaiyishujia** [comment]
> Hi, for the downloading of images from Dresden Image Database, the corresponding function is [here](https://github.com/JoiDvision/BNN_CamModel/blob/78c54fee661da51c14423f2284f25aa04a29c69b/dataloader_lib.py#L64).
> 
> However, this dataset is unfortunately not available anymore. So if you still want to use our method, you might need a different dataset, but the algorithm will still work the same. [RAISE](http://loki.disi.unitn.it/RAISE/download.html) and [The Forcheim Image Database](https://arxiv.org/abs/2011.02241l) are two possible substitutes.

thank you very much!
